// Deterministic test for AGENTS.md managed blocks + episode memory (no API key).
// Usage: bun run scripts/agent-memory-smoke.ts
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { refreshAgentsMd } from "../src/context/agents.ts";
import { listEpisodes, listPromotionCandidates, loadAgentsMemory, promoteCandidates, rememberEpisode } from "../src/context/agent-memory.ts";
import type { Message } from "../src/providers/types.ts";

let fail = false;
const check = (name: string, ok: boolean, extra = "") => {
  console.log(`${ok ? "✓" : "✗"} ${name}${extra ? ` — ${extra}` : ""}`);
  if (!ok) fail = true;
};

const dir = mkdtempSync(join(tmpdir(), "ob1-agent-memory-"));
try {
  writeFileSync(join(dir, "package.json"), JSON.stringify({ scripts: { start: "bun run src/index.ts", test: "bun test" } }));
  writeFileSync(join(dir, "bun.lock"), "");
  writeFileSync(join(dir, "AGENTS.md"), `# AGENTS.md

> Auto-generated by OB-1 on first run. **Edit freely** — legacy file.

## Stack
- stale

## Commands
- stale

## Key files (by reference centrality)
- stale

## Conventions
- Preserve this human note.
`);

  const migrated = refreshAgentsMd(dir, { projectFacts: ["Use Bun built-ins first."] });
  const first = readFileSync(join(dir, "AGENTS.md"), "utf8");
  check("legacy AGENTS.md migrates to managed project block", migrated.updated && first.includes("<!-- OB1:BEGIN project -->"));
  check("legacy AGENTS.md gains managed memory block", first.includes("<!-- OB1:BEGIN memory -->") && first.includes("Use Bun built-ins first."));
  check("legacy migration preserves human conventions", first.includes("Preserve this human note."));

  writeFileSync(join(dir, "AGENTS.md"), first + "\n## Local Notes\n- Keep this too.\n");
  refreshAgentsMd(dir, { projectFacts: ["Updated fact."] });
  const second = readFileSync(join(dir, "AGENTS.md"), "utf8");
  check("refresh replaces only managed memory content", second.includes("Updated fact.") && !second.includes("Use Bun built-ins first."));
  check("refresh preserves custom sections outside managed blocks", second.includes("## Local Notes\n- Keep this too."));

  writeFileSync(join(dir, "AGENTS.md"), "# Human-owned file\n\nNo OB-1 markers.\n");
  const human = refreshAgentsMd(dir, { projectFacts: ["should not write"] });
  check("human-owned AGENTS.md without markers is not changed", !human.updated && !readFileSync(join(dir, "AGENTS.md"), "utf8").includes("should not write"));

  rmSync(join(dir, "AGENTS.md"), { force: true });
  const history: Message[] = [
    { role: "assistant", content: [{ type: "tool_use", id: "bash-1", name: "run_bash", input: { command: "bun test" } }] },
    { role: "user", content: [{ type: "tool_result", tool_use_id: "bash-1", content: "exit 0\n2 tests passed" }] },
    { role: "assistant", content: [{ type: "tool_use", id: "browser-1", name: "browser_check", input: { url: "site/index.html" } }] },
    { role: "user", content: [{ type: "tool_result", tool_use_id: "browser-1", content: "✓ browser_check PASSED" }] },
    { role: "assistant", content: [{ type: "tool_use", id: "tasks-1", name: "update_tasks", input: { tasks: [{ content: "Verify", status: "completed" }] } }] },
    { role: "user", content: [{ type: "tool_result", tool_use_id: "tasks-1", content: "task list updated" }] },
    { role: "assistant", content: [{ type: "text", text: "Done. Known issue: follow-up by adding browser coverage." }] },
  ];
  const { episode } = rememberEpisode(dir, "verify episode memory", "solo", history);
  check("episode markdown is written", existsSync(join(dir, ".ob1", "episodes", `${episode.id}.md`)));
  check("episode list reads newest episode", listEpisodes(dir, 1)[0]?.id === episode.id);

  const memory = loadAgentsMemory(dir);
  check("successful check command updates project memory", memory.validatedChecks?.some((x) => x.includes("`bun test` passed")) === true);
  check("AGENTS.md is refreshed from episode memory", readFileSync(join(dir, "AGENTS.md"), "utf8").includes("Last episode"));

  const candidates = listPromotionCandidates(dir);
  check("promotion candidates are created from durable signals", candidates.some((c) => c.kind === "validated-check") && candidates.some((c) => c.kind === "known-issue"));
  check("behavior and quality-pattern candidates are created", candidates.some((c) => c.kind === "validated-behavior-check") && candidates.some((c) => c.kind === "quality-pattern"));
  const promoted = promoteCandidates(dir, "all");
  check("promotion writes candidates into memory", promoted.promoted.length === candidates.length && (promoted.memory.knownIssues?.length ?? 0) > 0);
  check("promotion writes behavior checks and quality patterns", (promoted.memory.validatedBehaviorChecks?.length ?? 0) > 0 && (promoted.memory.qualityPatterns?.length ?? 0) > 0);
  check("promoted candidates disappear from review list", listPromotionCandidates(dir).length === 0);
} finally {
  rmSync(dir, { recursive: true, force: true });
}

if (fail) { console.error("\n✗ agent-memory smoke FAILED"); process.exit(1); }
console.log("\n✓ agent-memory smoke passed (AGENTS managed blocks · episodes · review/promote)");
