#!/usr/bin/env bash
# Install OB-1 so you can just type `ob1` anywhere.
#
#   ./scripts/install.sh            # launcher (default) — full native features, runs via Bun from this repo
#   ./scripts/install.sh --binary   # self-contained executable — no Bun needed to run (pure-TS fallbacks)
#
# Picks a bin dir already on your PATH (prefers ~/.local/bin), and tells you how to fix PATH if needed.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
MODE="launcher"
[ "${1:-}" = "--binary" ] && MODE="binary"

command -v bun >/dev/null 2>&1 || { echo "✗ Bun is required to build OB-1 — install it from https://bun.sh"; exit 1; }

echo "→ installing dependencies"
(cd "$REPO" && bun install >/dev/null 2>&1) || (cd "$REPO" && bun install)

# Choose a bin dir: first one of these that's already on PATH + writable; else default to ~/.local/bin.
choose_bindir() {
  local candidates=("$HOME/.local/bin" "/usr/local/bin" "/opt/homebrew/bin" "$HOME/.bun/bin")
  for d in "${candidates[@]}"; do
    case ":$PATH:" in *":$d:"*) if [ -d "$d" ] && [ -w "$d" ]; then echo "$d"; return; fi ;; esac
  done
  echo "$HOME/.local/bin"
}
BINDIR="$(choose_bindir)"
mkdir -p "$BINDIR"
TARGET="$BINDIR/ob1"

if [ "$MODE" = "binary" ]; then
  echo "→ compiling standalone binary (this can take a moment)"
  (cd "$REPO" && bun run scripts/build-bin.ts "$TARGET")
  chmod +x "$TARGET"
else
  echo "→ installing launcher → $TARGET"
  cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# OB-1 launcher (generated by scripts/install.sh) — runs through Bun from the repo so native
# features (tree-sitter repo map, sqlite-vec KNN) work and updates are picked up automatically.
exec bun "$REPO/src/index.ts" "\$@"
EOF
  chmod +x "$TARGET"
fi

echo "✓ installed: $TARGET"
case ":$PATH:" in
  *":$BINDIR:"*) echo "  $BINDIR is on your PATH — open a terminal anywhere and run: ob1" ;;
  *) echo "  ⚠ $BINDIR is not on your PATH yet. Add this to your shell profile (~/.zshrc), then restart the shell:"
     echo "      export PATH=\"$BINDIR:\$PATH\"" ;;
esac
