// AGENTS.md — the always-loaded project memory index (R6 convergent standard; R3 index tier).
// On first run OB-1 generates a concise AGENTS.md from the detected stack, build/test commands,
// and the repo map. It is loaded (bounded) into every system prompt and is meant to be
// human-edited thereafter.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildRepoMap } from "./repomap.ts";

export interface ProjectInfo {
  stack: string[];
  build?: string;
  test?: string;
  run?: string;
}

function readFile(cwd: string, f: string): string | null {
  try { return readFileSync(join(cwd, f), "utf8"); } catch { return null; }
}

export function detectProject(cwd: string): ProjectInfo {
  const info: ProjectInfo = { stack: [] };
  const pkg = readFile(cwd, "package.json");
  if (pkg) {
    const pm = readFile(cwd, "bun.lock") || readFile(cwd, "bun.lockb") ? "bun run"
      : readFile(cwd, "pnpm-lock.yaml") ? "pnpm"
      : readFile(cwd, "yarn.lock") ? "yarn"
      : "npm run";
    info.stack.push(pm.startsWith("bun") ? "TypeScript / Bun" : "Node / TypeScript");
    try {
      const s = (JSON.parse(pkg).scripts ?? {}) as Record<string, string>;
      if (s.build) info.build = `${pm} build`;
      if (s.test) info.test = `${pm} test`;
      if (s.start) info.run = `${pm} start`;
    } catch { /* ignore */ }
  }
  if (readFile(cwd, "go.mod")) { info.stack.push("Go"); info.build ??= "go build ./..."; info.test ??= "go test ./..."; }
  if (readFile(cwd, "Cargo.toml")) { info.stack.push("Rust"); info.build ??= "cargo build"; info.test ??= "cargo test"; }
  if (readFile(cwd, "pyproject.toml") || readFile(cwd, "requirements.txt")) info.stack.push("Python");
  return info;
}

export function generateAgentsMd(cwd: string): string {
  const info = detectProject(cwd);
  let map;
  try { map = buildRepoMap(cwd, { maxFiles: 500 }); } catch { map = null; }
  const keyFiles = map ? map.files.slice(0, 10).map((f) => `- \`${f.path}\``).join("\n") : "";

  const cmds = [
    info.build ? `- build: \`${info.build}\`` : null,
    info.test ? `- test: \`${info.test}\`` : null,
    info.run ? `- run: \`${info.run}\`` : null,
  ].filter(Boolean).join("\n");

  return `# AGENTS.md

> Auto-generated by OB-1 on first run. **Edit freely** — this is your project's always-loaded
> memory index. Keep it concise (under ~200 lines); put detailed notes in topic files and let
> OB-1's long-term memory hold the rest.

## Stack
${info.stack.length ? info.stack.map((s) => `- ${s}`).join("\n") : "- (not detected)"}

## Commands
${cmds || "- (none detected — add build/test/run here)"}

## Key files (by reference centrality)
${keyFiles || "- (none detected)"}

## Conventions
- (add project-specific conventions, gotchas, and house style here)
`;
}

/** Create AGENTS.md if missing. Returns whether it was created. */
export function ensureAgentsMd(cwd: string): { path: string; created: boolean } {
  const path = join(cwd, "AGENTS.md");
  if (existsSync(path)) return { path, created: false };
  writeFileSync(path, generateAgentsMd(cwd));
  return { path, created: true };
}

/** Load AGENTS.md, bounded to the first maxLines/maxBytes (Memory Bank index pattern). */
export function loadAgentsMd(cwd: string, maxLines = 200, maxBytes = 25_000): string | null {
  const path = join(cwd, "AGENTS.md");
  if (!existsSync(path)) return null;
  let txt = readFileSync(path, "utf8").split("\n").slice(0, maxLines).join("\n");
  if (txt.length > maxBytes) txt = txt.slice(0, maxBytes);
  return txt;
}
